# Generated by Django 4.2.5 on 2023-09-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='role',
            field=models.CharField(choices=[('CS', 'Клиент'), ('SC', 'Сервисная Компания'), ('MR', 'Менеджер')], default=None, max_length=2, verbose_name='Роль'),
        ),
    ]
